"""empty message

Revision ID: 71de61ed14a6
Revises: 5de4053b45f5
Create Date: 2023-08-28 16:58:25.999985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '71de61ed14a6'
down_revision: Union[str, None] = '5de4053b45f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('slug', mysql.VARCHAR(length=300), nullable=False))
    # ### end Alembic commands ###
