"""empty message

Revision ID: 98105ac960cb
Revises: 264f198d1c17
Create Date: 2023-09-01 21:16:44.102400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98105ac960cb'
down_revision: Union[str, None] = '264f198d1c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    # ### end Alembic commands ###
